version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    depends_on:
      - api

  api:
    image: your-api-image
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - API_URL=http://api:5000
    volumes:
      - ./api:/app

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend